spring.application.name=backend

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/naas_db
spring.datasource.username=postgres
spring.datasource.password=Lalith123

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=MyNaasSecretKeyThatIsAtLeast32CharactersLong!2026
jwt.expiration=86400000

# Google Fleet Routing Configuration
google.fleet.service-account-key=classpath:swe-naas-7bbde297e808.json

# File Upload Configuration
file.upload-dir=/Users/lalith/snu/sem6/swe/lab/code_implimentaion/backend/src/files